(() => {
  'use strict';
  window.ScriptConfig = {
    dice: {
      maxDice: 9,
      maxSides: 100,
      obfOffset: 1193,
      buttonAfterSelector: '#button-addition',
      buttonSelector: '#dice-roll-btn',
      buttonIcon: '/i/blank.gif',
    },
    fontResizer: {
      fontSelector: '.post-content, #main-reply',
      storageKey: 'postFontSize',
      minSize: 10,
      maxSize: 38,
      defaultSize: 14,
      insertAfterSelector: '',
      defaultAnchorSelector: '.post h3 strong',
    },
    balanceTool: {
      ui: {
        insertAfterSelector: '.post-rating',
        openButtonText: 'Баланс',
        runButtonText: 'Выполнить',
        labels: { type: 'Тип операции', amount: 'Количество' },
        inputStyle: 'color:#111 !important',
      },
      access: { allowedTopicIds: ['1', '2', '3'], allowedGroupIds: [1] },
      profileFieldKey: 'fld1',
      operations: [
        { title: 'Начисление', factor: 1, topics: 'all' },
        { title: 'Списание', factor: -1, topics: 'all' },
      ],
      decimals: 2,
      decoratePost: true,
      simulateOnly: false,
      rate: { max: 10, windowMs: 300000 },
      wrapper: {
        start: `[spoiler="[b]ОБРАБОТАНО[/b] ({{ADMIN_NAME}}) — было: {{CACHE_BEFORE}}, стало: {{CACHE_AFTER}}"]\n[b]Операция:[/b] авто&#8209;начисление из темы банка\n\n`,
        end: `\n[/spoiler]`,
      },
      adminAliases: { 1: 'АМС' },
      endpoints: {
        profileUrl: (uid) => `/profile.php?section=fields&id=${uid}`,
        profileFormSelector: 'form[action*="profile.php"][method="post"]',
        postEditUrl: (pid) => `/edit.php?id=${pid}&action=edit`,
        postEditFormSelector: 'form[action*="edit.php"][method="post"]',
        postEditMessageField: 'req_message',
      },
      requestTimeoutMs: 15000,
      toastDurationMs: 2200,
    },
    bbcodeMask: {
      blockTag: 'mask',
      defaultAvatar: 'https://i.imgur.com/bQuC3S1.png',
      buttonIcon: 'https://i.imgur.com/ONu0llO.png',
      storageKey: 'maskListUser',
      storageLimit: 5,
      localDraftKey: 'maskFormDraft',
      safeProtocols: ['http:', 'https:', 'mailto:', 'ftp:'],
      allowedGroups: [1, 2],
      userFieldOrder: [
        'pa-author',
        'pa-title',
        'pa-avatar',
        'custom-field',
        'post-sig',
      ],
      bbTagMap: { b: 'strong', i: 'em', u: 'u', s: 's' },
      forumAccess: {},
      forumAccessExtended: {},
      guestAccess: ['Архив игровых тем', 'Архив неигровых тем'],
      fields: {
        author: {
          tags: ['nick', 'nic', 'o'],
          class: 'pa-author',
          max: 25,
          label: 'Ник',
          defaultCode: 'Имя Персонажа',
          type: 'text',
        },
        status: {
          tags: ['status', 'sta', 'q'],
          class: 'pa-title',
          max: 50,
          label: 'Статус',
          defaultCode: 'Профессия, раса, состояние',
          type: 'text',
        },
        avatar: {
          tags: ['icon', 'ava', '9'],
          class: 'pa-avatar',
          label: 'Аватар',
          defaultCode: 'https://i.imgur.com/bQuC3S1.png',
          type: 'avatar',
        },
        signature: {
          tags: ['sign', 'sgn', 't'],
          class: 'post-sig',
          label: 'Подпись',
          defaultCode: '[b]Информация о персонаже[/b]',
          type: 'bbcode',
        },
        custom: {
          tags: ['custom', 'custom-field'],
          class: 'custom-field',
          label: 'Кастомное поле',
          max: 40,
          defaultCode: 'Текст для кастомного поля',
          type: 'html',
        },
      },
      sanitize: {
        allowedTags: [
          'b',
          'i',
          'u',
          's',
          'strong',
          'em',
          'a',
          'img',
          'br',
          'span',
          'div',
          'sup',
          'sub',
          'mark',
          'abbr',
          'blockquote',
          'details',
          'summary',
          'ul',
          'ol',
          'li',
          'table',
          'tr',
          'td',
          'hr',
        ],
        allowedAttrs: {
          a: ['href', 'target', 'rel'],
          img: ['src', 'alt'],
          abbr: ['title'],
          mark: ['title'],
          blockquote: ['title'],
          details: ['title'],
          summary: ['title'],
          span: ['style'],
          div: ['style'],
        },
        allowedInlineStyles: [
          'color',
          'text-align',
          'font-size',
          'font-family',
        ],
        blockSvgInImg: true,
        safeProtocols: ['http:', 'https:', 'ftp:', 'mailto:'],
      },
      selectors: {
        post: '.post',
        content: '.post-content',
        profile: '.post-author ul',
        toolbarRow: '#form-buttons tr, #form-buttons',
        textarea: [
          '#message',
          'textarea[name="req_message"]',
          'textarea[name="message"]',
          'textarea:not([readonly]):not([disabled])',
        ],
        previewBox: '#post-preview',
      },
      maxCacheEntries: 300,
    },
    bbcodeFloat: {
      buttonAfterSelector: 'td#button-link',
      postContentSelector: '.post-content',
      previewSelector: '#post-preview .post-content',
      toolbarId: 'float-toolbar',
      floatButtonId: 'button-float',
      buttonTitle: 'Обтекание',
      toolbarTitle: 'Обтекание',
      buttonIcon: '/i/blank.gif',
      buttons: {
        left: { title: 'Слева', iconClass: 'fa-solid fa-indent' },
        right: {
          title: 'Справа',
          iconClass: 'fa-solid fa-indent',
          iconStyle: 'transform:scaleX(-1)',
        },
      },
      floatStyles: {
        left: 'float:left;margin:25px;text-align:left;display:inline-block;max-width:90%',
        right:
          'float:right;margin:25px;text-align:right;display:inline-block;max-width:90%',
      },
      floatRx: /\[float=(left|right)\]([\s\S]{1,11000}?)\[\/float\]/gi,
    },
    bbcodeHideProfile: {
      allowedGroups: [1, 2, 4],
      selectors: {
        post: '.post',
        postBody: '.post-body',
        buttonInsert: '',
      },
      buttonIcon: '/i/blank.gif',
      tag: '[hideprofile]',
      hideClass: 'hide-profile',
      buttonText: 'Скрыть минипрофиль',
    },
    bbcodeIndent: {
      bbcode: '[indent]',
      marginLeft: '2em',
      selectors: '.post-content, #post-preview .post-content',
      buttonAfterSelector: '#button-strike',
      buttonId: 'button-indent-btn',
      buttonTitle: 'Отступы',
      buttonIcon: '/i/blank.gif',
    },
    bbcodeJustify: {
      insertAfterSelector: '#button-right',
      buttonId: 'button-justify',
      buttonIcon: '/i/blank.gif',
      title: 'Выравнивание по ширине',
      bbcodeOpen: '[align=justify]',
      bbcodeClose: '[/align]',
    },
    characterModal: {
      id: 'character-modal',
      classes: {
        wrap: 'modal__wrap',
        bg: 'modal__bg',
        open: 'open',
        hidden: 'hidden',
        tab: 'modal__tab',
        active: 'active',
        tabContent: 'modal__content',
        tabs: 'modal__tabs',
      },
      delays: { open: 20, close: 220 },
      ajaxFolder: 'pages/',
      charset: 'windows-1251',
    },
    cleanQuote: {
      selectors: {
        post: (id) => `#p${id}`,
        signature: '.post-sig',
        lastEdit: 'p.lastedit',
        content: '.post-content',
        textarea: 'textarea',
      },
      replacements: [
        { from: /<br\s*\/?>/gi, to: '\n' },
        { from: /<strong>/gi, to: '[b]' },
        { from: /<\/strong>/gi, to: '[/b]' },
      ],
    },
    copyCode: {
      buttonText: 'Скопировать код',
      doneText: 'Скопировано',
      resetTimeout: 1200,
    },
    chronoParser: {
      forumsWithGames: { active: [5, 10, 14], done: [7] },
      currentYear: 2025,
      topicsPerRequest: 100,
      postsPerRequest: 100,
      apiBase: '/api.php',
      pagePath: '/pages/chrono',
      mountId: 'chrono-root',
      headingActive: 'Активные эпизоды',
      headingDone: 'Завершённые эпизоды',
    },
    cursorManager: {
      insertAfterSelector: '#pun-crumbs1',
      storageKey: 'selectedCursor',
      respectReducedMotion: true,
      defaultCursorImg: 'https://upforme.ru/uploads/001c/89/3b/2/926162.png',
      cursors: [
        { id: 'auto', title: 'Стандартный', value: 'auto' },
        { id: 'pointer', title: 'Указатель', value: 'pointer' },
        { id: 'cross', title: 'Крест', value: 'crosshair' },
        {
          id: 'red',
          title: 'Красный',
          url: 'https://upforme.ru/uploads/001c/89/3b/2/407488.png',
          x: 2,
          y: 2,
          fallback: 'auto',
        },
        {
          id: 'paw',
          title: 'Лапка',
          url: 'https://upforme.ru/uploads/001c/89/3b/2/695986.png',
          x: 6,
          y: 2,
          fallback: 'pointer',
        },
        {
          id: 'dagger',
          title: 'Кинжал',
          url: 'https://upforme.ru/uploads/001c/89/3b/2/33066.png',
          x: 3,
          y: 1,
          fallback: 'default',
        },
        {
          id: 'comet',
          title: 'Комета (шлейф)',
          type: 'trail',
          dotCount: 10,
          size: 10,
          color: 'rgba(0,132,255,.85)',
          decayMs: 500,
        },
      ],
    },
    defaultAvatars: {
      DEFAULT_AVATAR: 'https://upforme.ru/uploads/001c/73/bf/2/862383.jpg',
      avatarByRole: {
        0: 'https://upforme.ru/uploads/001c/0a/76/4/246574.jpg',
        3: 'https://upforme.ru/uploads/001c/0a/76/4/916153.jpg',
      },
    },
    episodeTracker: {
      allowedGroupIds: [1, 2, 4],
      oneDayMs: 86400000,
      maxParticipants: 10,
      selectors: {
        anchor: '#h-uploads',
        insertAfter: '',
      },
    },
    forumChronology: {
      endpoint: '/api.php?method=forum.chronology',
      containerSelector: '#forumChronology',
    },
    forumTopicsDivider: {
      selectors: {
        forum: '#pun-viewforum',
        stickyRows: 'tr[class$="isticky"]',
        stickyLabel: '.stickytext',
      },
      headers: {
        important: 'Важные темы',
        regular: 'Темы форума',
      },
    },
    gamepostCounter: {
      viewerGroups: [1, 2, 4],
      includeFirstPost: false,
      forumsRules: {
        defaultMode: 'all',
        perForum: new Map([
          ['1', { mode: 'all' }],
          // ['10', { mode: 'include', topics: new Set([27]) }],
          // ['14', { mode: 'exclude', topics: new Set([101]) }],
        ]),
      },
      ui: {
        showBadgesInTopic: true,
        badgeSource: 'week',
        profileBadgeSource: 'week',
        fieldId: 3,
        maxUsersToDecorate: 40,
        launcherAfter: '#button-addition',
        launcherText: 'Статистика постов',
        forumsOnly: [1],
      },
      backend: {
        endpoint: 'https://feathertail.ru/gamestats/index.php',
        subscription: 'FTTESTS',
        tableKey: 'ks-global',
        limit: 20,
        scope: 'site',
      },
      settingsMenuSection: 'settings',
      toggleInsertAfter: '',
    },
    guestAddress: {
      selector: '.pa-author',
      group: 3,
    },
    imageUploader: {
      anchorSelector: 'p.areafield.required .resizable-textarea > span',
      replyTextareaSelector: '#main-reply',
      defaultHost: 'forum',
      allowedMimes: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
      maxFilesPerBatch: 20,
      defaultInsertFormat: 'img',
      showOnDemand: true,
      storage: { host: 'rfu:host', fmt: 'rfu:fmt' },
      forumUpload: {
        endpoint: '/upload',
        token: () => window.ForumAPITicket || '',
        buildUrl: (fname) => helpers.buildForumUploadsURL(fname),
        headers: () => ({}),
      },
      enabledHosts: ['forum', 'imgbb'],
      imgbb: { key: 'c5697b050c00a5dcdc012ce325afdd35' },
    },
    insertAddress: {
      snippet: '[b]{{USER}}[/b], ',
      selector: 'textarea',
    },
    multiaccount: {
      allowedGroups: [1, 2, 4],
      selectors: {
        navMenu: '#pun-navlinks ul.container',
        logout: '#navlogout',
      },
      ids: {
        navProfiles: 'navprofiles',
        usernameInput: 'multiacc-username-input',
        passwordInput: 'multiacc-password-input',
      },
      classes: {
        profileMenu: 'multiacc-profilemenu',
        deleteBtn: 'multiacc-delete-btn',
        active: 'multiacc-active',
        overlay: 'multiacc-overlay',
        dialog: 'multiacc-dialog',
      },
      storageKeys: {
        accounts: 'multiacc_accounts',
        active: 'multiacc_active_user',
        key: 'multiacc_key',
      },
      loginUrl: 'login.php?action=in',
      formFields: {
        formSent: 'form_sent',
        redirectUrl: 'redirect_url',
        username: 'req_username',
        password: 'req_password',
      },
      texts: {
        menuTitle: 'Аккаунты',
        addAccount: 'Добавить аккаунт',
        usernameLabel: 'Логин:',
        passwordLabel: 'Пароль:',
        addButton: 'Добавить',
        cancelButton: 'Отмена',
        duplicateAccount: 'Аккаунт с таким логином уже существует!',
        deleteButton: 'X',
      },
    },
    mutualPR: {
      ALLOWED_GROUPS: [1, 2, 4, 5],
      TARGET_TOPIC: 'Техническая тема',
      PR_TEMPLATES: [
        `[align=center][url=YOUR_LINK][img]YOUR_IMG[/img][/url][/align]`,
      ],
      COPY_SUCCESS_TEXT: 'Наш шаблон и ссылка на взаимную рекламу скопированы!',
      BUTTON_LABEL: 'Взаимная реклама',
    },
    newMessagesLink: {
      allowedGroupIds: [1, 2, 4],
      url: '/search.php?action=show_new',
      text: 'Новые сообщения',
    },
    postPreview: {
      debounceDelay: 600,
      toggleCookie: '_PreviewToggle',
      allowedForums: [1, 5, 10],
      toggleInsertAfter: '#form-buttons',
      settingsMenuSection: 'settings',
      checkInterval: 800,
    },
    postsCharCounter: {
      allowedForumIds: [1, 3],
      storageKey: 'postsCharCounterToggle',
      toggleInsertAfter: '',
      toggleLabel: 'Счётчик символов в постах',
      settingsMenuSection: 'settings',
      selectors: {
        posts: '.post:not(.topicpost)',
        insertAfter: '',
        defaultAfter: '.post-content',
        maskSelectors: ['.post-mask', '.mask', '.pl-mask', '[data-mask]'],
      },
      flags: { stripMaskBBCode: true },
    },
    prQuickLogin: {
      login: 'PR',
      pass: '1111',
      redirectUrl: 'https://feathertailtests.rusff.me/viewtopic.php?id=2',
      selectors: {
        btn: '#pr-quick-login',
        navLogin: '#navlogin',
        form: 'form[action*="login"]',
        userInput: 'input[name="req_username"]',
        passInput: 'input[name="req_password"]',
        submitInput: 'input[type="submit"]',
        redirectField: 'input[name="redirect_url"]',
      },
    },
    quoteBubble: {
      topicId: 'pun-viewtopic',
      postSel: '.post[id]',
      bubbleId: 'quote-bubble',
      iconUrl: 'http://www.iconsearch.ru/uploads/icons/crystalclear/16x16/comment.png',
      text: 'Цитировать',
      offsetX: 6,
      offsetY: 4,
      margin: 6
    },
    quotePostLink: {
      selectors: {
        cite: '.quote-box>cite',
        inlineQuote: '#pun-viewtopic .pl-quote > a',
        post: (id) => `.post${id}`,
        postRoot: '.post',
      },
      linkTemplates: {
        sameTopic: (postId) => postId,
        otherTopic: (pid, postId) => `/viewtopic.php?pid=${pid}${postId}`,
      },
    },
    replaceDash: {
      paragraphSelector: '.post-content p',
      dashRegex: /(^|[\s\u00A0])-(?=[\s\u00A0])/g,
    },
    replaceQuotes: {
      selector: '.post-content p',
      regex: /"([^"]*?)"/g,
    },
    replyCharCounter: {
      settingsMenuSection: 'settings',
      toggleInsertAfter: '',
      selectors: {
        textarea: '#main-reply',
        insertAfter: '',
        defaultBefore: '.formsubmit',
      },
      options: {
        stripMaskBBCode: true,
        useGraphemeCounter: true,
        watchProgrammaticChanges: true,
      },
    },
    replyHotkeys: {
      selectors: {
        textarea: '#main-reply',
        insertAfter: '.formsubmit',
        defaultBefore: '.formsubmit',
        submit: '.submit',
      },
      texts: {
        trigger: '?',
        title: 'Горячие клавиши',
        close: 'Esc',
      },
      HOTKEYS: [
        ['Ctrl+KeyB', ['[b]', '[/b]', 'жирный']],
        ['Ctrl+KeyI', ['[i]', '[/i]', 'курсив']],
        ['Ctrl+KeyU', ['[u]', '[/u]', 'подчёркнутый']],
        ['Ctrl+KeyS', ['[s]', '[/s]', 'зачёркнутый']],
        ['Ctrl+KeyL', ['[align=left]', '[/align]', 'выравнивание влево']],
        ['Ctrl+KeyR', ['[align=right]', '[/align]', 'выравнивание вправо']],
        ['Ctrl+KeyE', ['[align=center]', '[/align]', 'выравнивание по центру']],
        ['Ctrl+KeyK', ['[url=https://]', '[/url]', 'ссылка']],
        ['Ctrl+KeyG', ['[spoiler="…"]', '[/spoiler]', 'спойлер']],
        ['Ctrl+KeyH', ['[hide=999999]', '[/hide]', 'скрытый текст']],
        ['Alt+KeyV', ['[video]', '[/video]', 'видео']],
        ['Ctrl+KeyQ', ['[quote]', '[/quote]', 'цитата']],
        ['Ctrl+BracketLeft', ['[code]', '[/' + 'code]', 'код']],
        ['Alt+KeyC', ['[color=maroon]', '[/color]', 'цвет']],
        ['Alt+KeyT', ['[table][tr][td]', '[/td][/tr][/table]', 'таблица']],
        ['Ctrl+Shift+KeyD', ['[add]', '', 'добавлено спустя']],
        ['Ctrl+Shift+KeyA', ['[abbr="…"]', '[/abbr]', 'поясняющий текст']],
        ['Ctrl+Shift+KeyM', ['[mark]', '[/mark]', 'маркированный текст']],
        ['Alt+KeyH', ['[hr]', '', 'горизонтальная линия']],
        ['Ctrl+Enter', [null, null, 'отправить сообщение']],
      ],
    },
    scrollRails: {
      classes: {
        up: '.scroll-rail.rail-up',
        down: '.scroll-rail.rail-down',
      },
      edgeOffset: 80,
    },
    settingsMenu: {
      texts: {
        open: 'Меню',
      },
      sections: {
        links: {
          title: 'Полезные ссылки',
          items: [
            {
              text: 'Правила форума',
              children: [
                { text: 'Правила раздела 1', href: '/viewtopic.php?id=1' },
                {
                  text: 'Правила раздела 2',
                  href: 'https://mayakfor.me/search.php?action=show_new',
                },
                {
                  text: 'Правила раздела 3',
                  href: 'https://mayakfor.me/viewtopic.php?id=2300&p=35#p200656',
                },
              ],
            },
            {
              text: 'BBCode справка',
              href: 'https://bbcode.org/reference.php',
              target: '_blank',
              rel: 'noopener noreferrer',
            },
          ],
        },
        themes: {
          title: 'Темы',
          mount: 'themeSwitcher:initSection',
        },
        settings: {
          title: 'Настройки',
        },
        cursors: {
          title: 'Курсоры',
          mount: 'cursorManager:initSection',
        },
      },
    },
    stickerPack: {
      dataUrl: 'https://forumstatic.ru/files/001c/73/bf/62093.txt?v=4',
      buttonAfterId: 'button-smile',
      buttonIcon: 'https://forumstatic.ru/files/001c/73/bf/87441.svg',
      myTabName: 'Свои',
      storageKey: 'stickerPackUserData',
      hideMyGroupId: 3,
      maxJsonSize: 65000,
      apiUrl: '/api.php',
      apiSetMethod: 'storage.set',
      apiGetMethod: 'storage.get',
    },
    textReplace: {
      rules: [
        {
          selector: '#navadmin',
          search: 'Администрирование',
          replace: 'Амс',
        },
        {
          selector: 'li.item1 span',
          search: 'Всего тем: ',
          replace: 'Тем: ',
        },
        {
          selector: 'li.item2 span',
          search: 'Всего сообщений: ',
          replace: 'Сообщений: ',
        },
        {
          selector: 'li.item3 span',
          search: 'Зарегистрированных пользователей: ',
          replace: 'Жителей: ',
        },
        {
          selector: 'li.item4 span',
          search: 'Последним зарегистрировался: ',
          replace: 'Приветствуем: ',
        },
      ],
    },
    themeSwitcher: {
      storage: { key: 'mybb.display.v1', instance: '' },
      defaults: { style: 'classic', scheme: 'light', view: 'desktop' },
      styles: [
        { id: 'classic', label: 'Classic' },
        { id: 'holiday', label: 'Holiday' }
      ],
      selectors: {
        root: 'html',
        targets: {
          style: 'html',
          scheme: 'body',
          view: 'html'
        },
        controls: {
          style: '[data-display-style]',
          scheme: '[data-display-scheme]',
          view: '[data-display-view]',
          forceMobileCheckbox: '#forceMobileToggle'
        },
        ui: {
          schemeMount: '#stylelist',
          styleMount:  '[data-style-mount]',
          styleMountId: 'ts-style-mount'
        }
      },
      classes: {
        stylePrefix: '',
        schemeLight: 'light',
        schemeDark:  'dark',
        forceMobile: 'force-mobile',
        activeControl: 'is-active',
        styleMount: 'ts-style-mount',
        styleButton: 'ts-style-btn',
        styleButtonPrefix: 'ts-style-',
        schemeButton: 'ts-scheme-btn'
      }
    }
  };
})();


