(() => {
  'use strict';
  window.ScriptConfig = {
    adminBank: {
      endpoints: {
        bankApiUrl: 'https://feathertail.ru/ks/bank/bank-api.php',
        forumApiBase: '/api.php',
        profileUrl: (uid) => `/profile.php?section=fields&id=${uid}`,
        profileFormSelector: 'form[action*="profile.php"][method="post"]',
      },
      profile: {
        moneyFieldName: 'form[fld4]',
        decimals: 2,
      },
      requestTimeoutMs: 15000,
      selectors: {
        root: '#ks-bank-admin-root',
        messages: '#ks-bank-admin-messages',
        summaryBox: '#ks-bank-admin-summary',
        list: '#ks-bank-admin-list',
        reloadBtn: '#ks-bank-admin-reload',
        statusFilter: '#ks-bank-admin-status',
        searchInput: '#ks-bank-admin-search',
      },
    },
    adminGamepostRecount: {
      forumIds: [10, 13, 11, 12, 17, 18],
      includeFirstPost: false,
      apiBase: '/api.php',
      topicsPerRequest: 100,
      postsPerRequest: 100,
      delayBetweenRequestsMs: 200,
      retryAttempts: 2,
      retryBaseDelayMs: 800,
      logToConsole: true,
      selectors: {
        runButton: '#ks-recount-run',
        saveButton: '#ks-recount-save',
        logBox: '#ks-recount-result',
        summaryBox: '#ks-recount-progress',
      },
      backend: {
        endpoint: 'https://feathertail.ru/gamestats/index.php',
        method: 'recalc',
        subscription: 'KSPIRITS-TEST',
        tableKey: 'ks-global',
      },
    },
    adminGamepostReward: {
      forumIds: [10, 11, 12, 13, 17],
      includeFirstPost: false,
      apiBase: '/api.php',
      topicsPerRequest: 100,
      postsPerRequest: 100,
      delayBetweenRequestsMs: 250,
      retryAttempts: 3,
      retryBaseDelayMs: 900,
      logToConsole: true,
      baseReward: 10,
      fastMultiplier: 1.5,
      fastThresholdSeconds: 24 * 3600,
      episodeForumId: 17,
      episodeCompletedForumId: 17,
      endpoints: {
        bankApiUrl: 'https://feathertail.ru/ks/bank/bank-api.php',
        stateApiUrl: 'https://feathertail.ru/ks/rewards/rewards-state-api.php',
      },
      selectors: {
        runButton: '#ks-gpreward-run',
        applyButton: '#ks-gpreward-apply',
        previewBox: '#ks-gpreward-preview',
        summaryBox: '#ks-gpreward-summary',
        warningBox: '#ks-gpreward-warning',
        errorBox: '#ks-gpreward-error',
      },
      safety: {
        maxTopicPages: 5000,
        maxPostPagesPerTopic: 20000,
      },
    },
    adminUsersSync: {
      apiBase: 'https://feathertail.ru/gamestats/users-sync.php',
      timeoutMs: 30000,
      maxSkip: 500,
    },
    balanceTool: {
      ui: {
        insertAfterSelector: '.rsp_wrap',
        openButtonText: 'Баланс',
        runButtonText: 'Выполнить',
        labels: { type: 'Тип операции', amount: 'Количество' },
        inputStyle: 'color:#111 !important',
      },
      access: { allowedTopicIds: ['155', '233', '318', '393'], allowedGroupIds: [1, 2] },
      profileFieldKey: 'fld4',
      operations: [
        { title: 'Начисление', factor: 1, topics: 'all' },
        { title: 'Списание', factor: -1, topics: 'all' },
      ],
      decimals: 2,
      decoratePost: true,
      simulateOnly: false,
      rate: { max: 10, windowMs: 300000 },
      wrapper: {
        start: `[spoiler="[b]ОБРАБОТАНО[/b] ({{ADMIN_NAME}}) — было: {{CACHE_BEFORE}}, стало: {{CACHE_AFTER}}"]\n[b]Операция:[/b] авто&#8209;начисление из темы банка\n\n`,
        end: `\n[/spoiler]`,
      },
      adminAliases: { 2: 'Kayden Moore', 4: 'Red thread of fate' },
      endpoints: {
        profileUrl: (uid) => `/profile.php?section=fields&id=${uid}`,
        profileFormSelector: 'form[action*="profile.php"][method="post"]',
        postEditUrl: (pid) => `/edit.php?id=${pid}&action=edit`,
        postEditFormSelector: 'form[action*="edit.php"][method="post"]',
        postEditMessageField: 'req_message',
      },
      requestTimeoutMs: 15000,
      toastDurationMs: 2200,
    },
    bankShop: {
      forumBaseUrl: 'https://kindredspirits.ru/',
      storageKeyPrefix: 'ks-bank-cart-',
      endpoints: {
        configUrl: 'https://feathertail.ru/ks/bank/bank.json',
        apiUrl: 'https://feathertail.ru/ks/bank/bank-api.php',
      },
      selectors: {
        root: '#ks-bank-root',
        messages: '#ks-bank-messages',
        myRequestsMessages: '#ks-bank-requests-messages',
        spendList: '#ks-bank-spend-list',
        earnList: '#ks-bank-earn-list',
        cartSpend: '#ks-bank-cart-spend',
        cartEarn: '#ks-bank-cart-earn',
        balanceBox: '#ks-bank-balance',
        summaryBox: '#ks-bank-summary',
        generateBtn: '#ks-bank-generate',
        requestsRoot: '#ks-bank-requests',
        requestsList: '#ks-bank-requests-list',
        requestsToggle: '#ks-bank-requests-toggle',
        requestsToggleIcon: '#ks-bank-requests-toggle-icon',
      },
      restorePrompt:
        'Обнаружена незавершённая заявка банка. Восстановить корзину?',
    },
    bbcodeMask: {
      blockTag: 'mask',
      defaultAvatar: 'https://i.imgur.com/bQuC3S1.png',
      buttonIcon: 'https://i.imgur.com/ONu0llO.png',
      storageKey: 'maskListUser',
      storageLimit: 20,
      localDraftKey: 'maskFormDraft',
      safeProtocols: ['http:', 'https:', 'mailto:', 'ftp:'],
      allowedGroups: [1, 2, 6],
      userFieldOrder: [
        'pa-fld2',
        'pa-author',
        'pa-title',
        'pa-avatar',
        'post-sig',
        'pa-fld1',
      ],
      bbTagMap: { b: 'strong', i: 'em', u: 'u', s: 's' },
      forumAccess: {
        PR: ['Реклама'],
      },
      forumAccessExtended: {
        Админка: ['Админ', 'Модератор', 'Одарённый'],
        Гостевая: ['Админ', 'Модератор', 'Одарённый'],
        'Информация о мире': ['Админ', 'Модератор', 'Одарённый'],
        'Доска объявлений': ['Админ', 'Модератор', 'Одарённый'],
        Анкеты: ['Админ', 'Модератор', 'Одарённый'],
        'Личные дела': ['Админ', 'Модератор', 'Одарённый'],
        Канцелярия: ['Админ', 'Модератор', 'Одарённый'],
        'Тень прошлого': ['Админ', 'Модератор', 'Одарённый'],
        'Мгновения настоящего': ['Админ', 'Модератор', 'Одарённый'],
        'Веяние будущего': ['Админ', 'Модератор', 'Одарённый'],
        'Альтернативная ветвь': ['Админ', 'Модератор', 'Одарённый'],
        'Зона отдыха': ['Админ', 'Модератор', 'Одарённый'],
        Игровая: ['Админ', 'Модератор', 'Одарённый'],
        Блоги: ['Админ', 'Модератор', 'Одарённый'],
        'Книги судеб': ['Админ', 'Модератор', 'Одарённый'],
        'Прерванные нити': ['Админ', 'Модератор', 'Одарённый'],
        PR: ['Админ', 'Модератор', 'Одарённый'],
      },
      guestAccess: ['Книги судеб', 'Прерванные нити'],
      fields: {
        author: {
          tags: ['nick', 'nic'],
          class: 'pa-author',
          max: 25,
          label: 'Ник',
          defaultCode: 'Имя Персонажа',
          type: 'text',
        },
        status: {
          tags: ['status', 'sta'],
          class: 'pa-title',
          max: 50,
          label: 'Статус',
          defaultCode: 'Профессия, раса, состояние',
          type: 'text',
        },
        avatar: {
          tags: ['icon', 'ava'],
          class: 'pa-avatar',
          label: 'Аватар',
          defaultCode: 'https://i.imgur.com/bQuC3S1.png',
          type: 'avatar',
        },
        signature: {
          tags: ['sign', 'sgn', 'signature'],
          class: 'post-sig',
          label: 'Подпись',
          defaultCode: '[b]Информация о персонаже[/b]',
          type: 'bbcode',
        },
        race: {
          tags: ['race'],
          class: 'pa-fld2',
          label: 'Раса',
          defaultCode: '<div title=укажите расу по-русски>w/f/t/h</div>',
          type: 'html',
        },
        lz: {
          tags: ['lz'],
          class: 'pa-fld1',
          label: 'ЛЗ',
          defaultCode:
            '<div class=lz-name><a href=ссылка на профиль>Имя Фамилия</a>, возраст</div> <div class=lz-text>Текст ЛЗ</div>',
          type: 'html',
        },
      },
      sanitize: {
        allowedTags: [
          'b',
          'i',
          'u',
          's',
          'strong',
          'em',
          'a',
          'img',
          'br',
          'span',
          'div',
          'sup',
          'sub',
          'mark',
          'abbr',
          'blockquote',
          'details',
          'summary',
          'ul',
          'ol',
          'li',
          'table',
          'tr',
          'td',
          'hr',
        ],
        allowedAttrs: {
          a: ['href', 'target', 'rel'],
          img: ['src', 'alt'],
          abbr: ['title'],
          mark: ['title'],
          blockquote: ['title'],
          details: ['title'],
          summary: ['title'],
          span: ['style'],
          div: ['style', 'title', 'class'],
        },
        allowedInlineStyles: [
          'color',
          'text-align',
          'font-size',
          'font-family',
        ],
        blockSvgInImg: true,
        safeProtocols: ['http:', 'https:', 'ftp:', 'mailto:'],
      },
      selectors: {
        post: '.post',
        content: '.post-content',
        profile: '.post-author ul',
        toolbarRow: '#form-buttons tr, #form-buttons',
        textarea: [
          '#message',
          'textarea[name="req_message"]',
          'textarea[name="message"]',
          'textarea:not([readonly]):not([disabled])',
        ],
        previewBox: '#post-preview',
      },
      maxCacheEntries: 300,
    },
    bbcodeFloat: {
      buttonAfterSelector: 'td#button-link',
      postContentSelector: '.post-content',
      previewSelector: '#post-preview .post-content',
      toolbarId: 'float-toolbar',
      floatButtonId: 'button-float',
      buttonTitle: 'Обтекание',
      toolbarTitle: 'Обтекание',
      buttonIcon: '/i/blank.gif',
      buttons: {
        left: { title: 'Слева', iconClass: 'fa-solid fa-indent' },
        right: {
          title: 'Справа',
          iconClass: 'fa-solid fa-indent',
          iconStyle: 'transform:scaleX(-1)',
        },
      },
      floatStyles: {
        left: 'float:left;margin:25px;text-align:left;display:inline-block;max-width:90%',
        right:
          'float:right;margin:25px;text-align:right;display:inline-block;max-width:90%',
      },
      floatRx: /\[float=(left|right)\]([\s\S]{1,11000}?)\[\/float\]/gi,
    },
    bbcodeHideProfile: {
      allowedGroups: [1, 2, 6],
      selectors: {
        post: '.post',
        postBody: '.post-body',
        buttonInsert: '',
      },
      buttonIcon: '/i/blank.gif',
      tag: '[hideprofile]',
      hideClass: 'hide-profile',
      buttonText: 'Скрыть минипрофиль',
    },
    bbcodeImageInsert: {
      buttonAfterSelector: '#button-image',
      buttonId: 'button-image-insert',
      buttonTitle: 'Изображение',
      buttonIcon: '/i/blank.gif',
      bbcodeOpen: '[img]',
      bbcodeClose: '[/img]',
    },
    bbcodeIndent: {
      bbcode: '[indent]',
      marginLeft: '2em',
      selectors: '.post-content, #post-preview .post-content',
      buttonAfterSelector: '#button-strike',
      buttonId: 'button-indent-btn',
      buttonTitle: 'Отступы',
      buttonIcon: '/i/blank.gif',
    },
    bbcodeJustify: {
      insertAfterSelector: '#button-right',
      buttonId: 'button-justify',
      buttonIcon: '/i/blank.gif',
      title: 'Выравнивание по ширине',
      bbcodeOpen: '[align=justify]',
      bbcodeClose: '[/align]',
    },
    characterModal: {
      id: 'character-modal',
      classes: {
        wrap: 'modal__wrap',
        bg: 'modal__bg',
        open: 'open',
        hidden: 'hidden',
        tab: 'modal__tab',
        active: 'active',
        tabContent: 'modal__content',
        tabs: 'modal__tabs',
      },
      delays: { open: 20, close: 220 },
      ajaxFolder: 'pages/',
      charset: 'windows-1251',
      showAwards: true,
      awardsApi: 'https://core.rusff.me/rusff.php',
    },
    charactersParser: {
      forumsWithCharacters: [8],
      apiBase: '/api.php',
      topicsPerRequest: 100,
      postsPerRequest: 100,
      pageDelayMs: 200,
      retryAttempts: 2,
      retryBaseDelayMs: 800,
      pagePath: '/pages/characters',
      mountId: 'characters-root',
      cacheTtlMs: 30 * 60 * 1000,
      imageIndex: 2,

      ui: {
        title: 'Персонажи',
        filters: {
          name: 'Имя / Фамилия',
          age: 'Возраст',
          gender: 'Пол',
          race: 'Раса',
          status: 'Статус',
          clear: 'Сбросить',
          refresh: 'Обновить',
          sort: 'Сортировка',
        },
        sort: {
          nameAZ: 'Имя A&#8594;Я',
          ageAsc: 'Возраст: младше&#8594;старше',
          ageDesc: 'Возраст: старше&#8594;младше',
        },
        placeholders: {
          name: 'Например: Имя / Name',
          ageFrom: 'от',
          ageTo: 'до',
        },
        empty: 'Под подходящие фильтры ничего не найдено.',
        loadError:
          'Не удалось загрузить список персонажей. Попробуйте обновить.',
      },
    },
    charProfileTool: {
      access: {
        allowedForumIds: [7, 8, 9],
        allowedGroupIds: [1],
      },

      selectors: {
        insertAfter: 'input.button.preview[name="preview"]',
        lzSource: '.custom_tag_charpt, .char-pt, [data-bbcode="charpt"]',
      },

      ui: {
        fillProfileText: 'Заполнить поля',
        createPageText: 'Создать страницу',
        changeGroupText: 'Смена группы',
      },

      profile: {
        moneyDefault: '40',
        postsDefault: '0',
        targetGroupId: 6,
        fieldNames: {
          race: 'form[fld2]', // Вид
          title: 'form[fld1]', // Личное звание
          badge: 'form[fld3]', // Плашка
          money: 'form[fld4]', // Деньги
          posts: 'form[fld5]', // Игровые посты
        },
      },
      endpoints: {
        apiBase: '/api.php',
        profileUrl: (uid) => `/profile.php?section=fields&id=${uid}`,
        profileFormSelector: 'form[action*="profile.php"][method="post"]',
        adminProfileUrl: (uid) => `/profile.php?section=admin&id=${uid}`,
        adminEditPageUrl: (slug) =>
          `/admin_pages.php?edit_page=${encodeURIComponent(slug)}`,
        adminProfileFormSelector:
          'form[action*="profile.php?section=admin"][method="post"], form#profile11',
        adminAddPageUrl: '/admin_pages.php?action=adddel',
        adminAddPageFormSelector:
          'form[action*="admin_pages.php"][method="post"], form#addpage',
      },
      requestTimeoutMs: 15000,
    },
    copyCode: {
      buttonText: 'Скопировать код',
      doneText: 'Скопировано',
      resetTimeout: 1200,
    },
    chronoParser: {
      forumsWithGames: { active: [10, 11, 13], done: [17] },
      currentYear: 2025,
      topicsPerRequest: 100,
      postsPerRequest: 100,
      apiBase: '/api.php',
      pagePath: '/pages/chrono',
      mountId: 'chrono-root',
      headingActive: 'Активные эпизоды',
      headingDone: 'Завершённые эпизоды',
      seriesDefaultStyle: 'https://forumstatic.ru/files/001c/82/f2/24385.css',
      seriesStyles: {},
    },
    cursorManager: {
      insertAfterSelector: '#pun-crumbs1',
      storageKey: 'selectedCursor',
      respectReducedMotion: true,
      defaultCursorImg: 'https://upforme.ru/uploads/001c/89/3b/2/926162.png',
      cursors: [
        { id: 'auto', title: 'Стандартный', value: 'auto' },
        { id: 'pointer', title: 'Указатель', value: 'pointer' },
        { id: 'cross', title: 'Крест', value: 'crosshair' },
        {
          id: 'red',
          title: 'Красный',
          url: 'https://upforme.ru/uploads/001c/89/3b/2/407488.png',
          x: 2,
          y: 2,
          fallback: 'auto',
        },
        {
          id: 'paw',
          title: 'Лапка',
          url: 'https://upforme.ru/uploads/001c/89/3b/2/695986.png',
          x: 6,
          y: 2,
          fallback: 'pointer',
        },
        {
          id: 'dagger',
          title: 'Кинжал',
          url: 'https://upforme.ru/uploads/001c/89/3b/2/33066.png',
          x: 3,
          y: 1,
          fallback: 'default',
        },
        {
          id: 'comet',
          title: 'Комета (шлейф)',
          type: 'trail',
          dotCount: 10,
          size: 10,
          color: 'rgba(0,132,255,.85)',
          decayMs: 500,
        },
      ],
    },
    defaultAvatars: {
      DEFAULT_AVATAR: 'https://forumstatic.ru/files/001c/82/f2/64447.jpg',
      avatarByRole: {
        0: 'https://forumstatic.ru/files/001c/82/f2/23507.jpg',
        3: 'https://forumstatic.ru/files/001c/82/f2/50471.jpg',
      },
    },
    dice: {
      maxDice: 9,
      maxSides: 100,
      obfOffset: 1193,
      buttonAfterSelector: '#button-addition',
      buttonSelector: '#dice-roll-btn',
      buttonIcon: '/i/blank.gif',
    },
    domWrappers: {
      groups: [
        {
          rootSelector: '#pun-index .tcr',
          targetSelector: '.lastpost-link, .lastpost',
          wrapperClass: 'tcr-wrap',
        },
        {
          rootSelector: '#pun-stats',
          targetSelector: '.item1, .item2, .item3, .item4',
          wrapperClass: 'statsinfo',
        },
        {
          rootSelector: '.punbb .post .post-author',
          targetSelector: 'li.pa-title, .pa-avatar, .pa-fld1',
          wrapperClass: 'author-wrap',
        },
        {
          rootSelector: '#pun-main .post-author ul',
          targetSelector: '.pa-posts, .pa-respect, .pa-fld4, .pa-fld5',
          wrapperClass: 'wrap-resp',
        },
        {
          rootSelector: '.post-box',
          targetSelector: '.post-rating, .post-vote',
          wrapperClass: 'rsp_wrap',
        },
        {
          rootSelector: 'body',
          targetSelector: '#selectMobVers, #selectDescVers',
          wrapperClass: 'sty',
        },
      ],
    },
    episodeTracker: {
      allowedGroupIds: [1, 2, 6],
      oneDayMs: 86400000,
      maxParticipants: 10,
      selectors: {
        anchor: '#h-uploads',
        insertAfter: '',
      },
    },
    fieldTitleHints: {
      rules: [
        { selector: '.pa-fld4 .fld-name', title: 'деньги' },
        { selector: '.pa-fld5 .fld-name', title: 'игровые посты' },
        { selector: '.pa-posts .fld-name', title: 'сообщения' },
        { selector: '.pa-respect .fld-name', title: 'репутация' },
      ],
    },
    fontResizer: {
      fontSelector: '.post-content, #main-reply',
      extraSelectors: [
        '.post-box .custom_tag_katexttext',
        '.post-box .custom_tag_katext',
        '.post-box .custom_tag_kindredaca',
      ],
      storageKey: 'postFontSize',
      minSize: 10,
      maxSize: 38,
      defaultSize: 14,
      insertAfterSelector: '',
      defaultAnchorSelector: '.post h3 strong',
    },
    forumAccessGuard: {
      enabled: true,
      allowedGroupIds: ['1', '2', '4', '6'],
      protectedForumIds: ['8'],
      blockMode: 'redirect',
      redirectUrl: '/',
      hideRowsOnIndex: true,
      selectors: {
        forumRowIdPrefix: 'forum_f',
        mainContainer: '#pun-main, #brd-main, main, #container, body',
      },
      blockedMessageHTML:
        '<div style="max-width:720px;margin:64px auto;padding:24px;border:1px solid var(--hair,#ccc);border-radius:12px;background:var(--paper,#fff);font:16px/1.5 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;">' +
        '<h2 style="margin:0 0 12px;">Доступ ограничен</h2>' +
        '<p style="margin:0 0 12px;">У вас нет прав для просмотра этого раздела.</p>' +
        '<p style="margin:0;color:#666;">Если вы считаете, что это ошибка, свяжитесь с администрацией.</p>' +
        '</div>',
    },
    forumTopicsDivider: {
      selectors: {
        forum: '#pun-viewforum',
        stickyRows: 'tr[class$="isticky"]',
        stickyLabel: '.stickytext',
      },
      headers: {
        important: 'Важные темы',
        regular: 'Темы форума',
      },
    },
    gamepostCounter: {
      viewerGroups: [1, 2, 3, 4, 5, 6],
      includeFirstPost: false,
      forumsRules: {
        defaultMode: 'all',
        perForum: new Map([
          ['10', { mode: 'all' }],
          ['11', { mode: 'all' }],
          ['12', { mode: 'all' }],
          ['13', { mode: 'all' }],
          ['17', { mode: 'all' }],
          ['18', { mode: 'all' }],
          // ['10', { mode: 'include', topics: new Set([27]) }],
          // ['14', { mode: 'exclude', topics: new Set([101]) }],
        ]),
      },
      ui: {
        showBadgesInTopic: true,
        badgeSource: 'total',
        profileBadgeSource: 'total',
        fieldId: 5,
        maxUsersToDecorate: 200,
        launcherAfter: '#button-addition',
        launcherText: 'Статистика постов',
        forumsOnly: [2],
      },
      backend: {
        endpoint: 'https://feathertail.ru/gamestats/index.php',
        subscription: 'KSPIRITS-TEST',
        tableKey: 'ks-global',
        limit: 40,
        scope: 'site',
      },
      settingsMenuSection: 'settings',
      toggleInsertAfter: '',
    },
    giftsTool: {
      access: {
        adminAllowedTopicIds: ['233'],
        adminAllowedGroupIds: [1],
      },
      currency: {
        label: '$',
        profileFieldKey: 'fld4',
        decimals: 2,
      },
      order: {
        marker: 'KS_GIFT_ORDER:',
        version: 1,
        maxCommentLen: 255,
      },
      send: {
        delayMs: 650,
      },
      endpoints: {
        profileFieldsUrl: (uid) => `/profile.php?section=fields&id=${uid}`,
      },
      groups: {
        order: ['Новогодние', 'Дни рождения', 'Любовь'],
        otherTitle: 'Другое',
        rememberState: true,
      },
      giftsUrl: 'https://feathertail.ru/ks/bank/gifts.php',
      gifts: [],
    },
    guestAddress: {
      selector: '.pa-author',
      group: 3,
    },
    imageUploader: {
      anchorSelector: 'p.areafield.required .resizable-textarea > span',
      replyTextareaSelector: '#main-reply',
      defaultHost: 'forum',
      allowedMimes: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
      maxFilesPerBatch: 20,
      defaultInsertFormat: 'img',
      showOnDemand: true,
      storage: { host: 'rfu:host', fmt: 'rfu:fmt' },
      forumUpload: {
        endpoint: '/upload',
        token: () => window.ForumAPITicket || '',
        buildUrl: (fname) => helpers.buildForumUploadsURL(fname),
        headers: () => ({}),
      },
      enabledHosts: ['forum', 'imgbb'],
      imgbb: { key: '6230a29b3ea5f686064c2b5010146c36' },
    },
    insertAddress: {
      snippet: '[b]{{USER}}[/b], ',
      selector: 'textarea',
    },
    mobileThemeSwitcher: {
      themes: [
        {
          value: 'mobile',
          className: 'mobile',
          title: 'мобильная тема',
        },
      ],
      storageKey: 'selectedMobileTheme',
      insertAfterSelector: '#pun-crumbs2',
      settingsMenuSection: 'mobileThemes',
      containerId: 'mobile_theme_switcher',
      cookieName: null,
      cookiePath: '/',
      cookieDays: 365,
    },
    multiaccount: {
      allowedGroups: [1, 2, 6],
      selectors: {
        navMenu: '#pun-navlinks ul.container',
        logout: '#navlogout',
      },
      ids: {
        navProfiles: 'navprofiles',
        usernameInput: 'multiacc-username-input',
        passwordInput: 'multiacc-password-input',
      },
      classes: {
        profileMenu: 'multiacc-profilemenu',
        deleteBtn: 'multiacc-delete-btn',
        active: 'multiacc-active',
        overlay: 'multiacc-overlay',
        dialog: 'multiacc-dialog',
      },
      storageKeys: {
        accounts: 'multiacc_accounts',
        active: 'multiacc_active_user',
        key: 'multiacc_key',
      },
      loginUrl: 'login.php?action=in',
      formFields: {
        formSent: 'form_sent',
        redirectUrl: 'redirect_url',
        username: 'req_username',
        password: 'req_password',
      },
      texts: {
        menuTitle: 'Аккаунты',
        addAccount: 'Добавить аккаунт',
        usernameLabel: 'Логин:',
        passwordLabel: 'Пароль:',
        addButton: 'Добавить',
        cancelButton: 'Отмена',
        duplicateAccount: 'Аккаунт с таким логином уже существует!',
        deleteButton: 'X',
      },
    },
    mutualPR: {
      ALLOWED_GROUPS: [1, 2, 4, 5, 6],
      TARGET_TOPIC: 'Реклама',
      PR_TEMPLATES: [
        `[align=center][url=https://kindredspirits.ru][img]https://forumstatic.ru/files/001c/82/f2/21734.jpg[/img][/url][/align]
[align=center][i]Kindred Spirits. Место, где можно отдохнуть душой.[/i][/align]
[align=center]&#10070; авторский мир    &#10070; мистика    &#10070; академия      &#10070; рисованные внешности  &#10070; 18+[/align]`,
      ],
      COPY_SUCCESS_TEXT: 'Наш шаблон и ссылка на взаимную рекламу скопированы!',
      BUTTON_LABEL: 'Взаимная реклама',
    },
    newMessagesLink: {
      allowedGroupIds: [1, 2, 6],
      url: '/search.php?action=show_new',
      text: 'Новые сообщения',
    },
    postPreview: {
      debounceDelay: 2000,
      toggleCookie: '_PreviewToggle',
      allowedForums: [10, 11, 13],
      toggleInsertAfter: '#form-buttons',
      settingsMenuSection: 'settings',
      checkInterval: 100,
    },
    postsCharCounter: {
      allowedForumIds: [10, 11, 12, 13],
      allowedGroupIds: [1, 2, 3, 4, 5, 6],
      storageKey: 'postsCharCounterToggle',
      toggleInsertAfter: '',
      toggleLabel: 'Счётчик символов в постах',
      settingsMenuSection: 'settings',
      selectors: {
        posts: '.post:not(.topicpost)',
        insertAfter: '',
        defaultAfter: '.post-content',
        maskSelectors: ['.post-mask', '.mask', '.pl-mask', '[data-mask]'],
      },
      flags: { stripMaskBBCode: true },
    },
    prQuickLogin: {
      login: 'PR',
      pass: '1111',
      redirectUrl: 'https://kindredspirits.ru/viewtopic.php?id=415',
      selectors: {
        btn: '#pr-quick-login',
        navLogin: '#navlogin',
        form: 'form[action*="login"]',
        userInput: 'input[name="req_username"]',
        passInput: 'input[name="req_password"]',
        submitInput: 'input[type="submit"]',
        redirectField: 'input[name="redirect_url"]',
      },
    },
    quicktip: {
      enabled: true,
      delayMs: 1200,
      speedMs: 300,
      xOffset: 26,
      yOffset: -5,
      defaultTitle: 'подсказка',
      reuseTooltip: true,
      useDelegation: true,
      tooltipId: 'tooltip',
      selectors: [
        'a[title]',
        'img[title]',
        'abbr[title]',
        'div[title]',
        'span[title]',
      ],
    },
    quickReputation: {
      enabled: true,
      addComment: true,
      behavior: {
        ratingClickMode: 'ajax+default',
        openDefaultWithCtrlClick: true,
      },
      selectors: {
        post: '.post',
        ratingLink: '.post-rating p > a',
        postVoteBlock: 'div.post-vote',
        postVoteLink: 'div.post-vote p > a',
        emailProfileLink: '.pl-email a[href*="profile.php?"]',
        respectField: '.pa-respect',
        positiveField: '.pa-positive',
        reputationSendBtn: '#reputationButtonSend',
      },
      classes: {
        noNull: 'noNull',
      },
      texts: {
        plusNoCommentTitle: 'Плюс без комментария',
        plusWithCommentTitle: 'Плюсики с комментарием',
        ignoreAlertSubstring: 'Мы не смогли сохранить ваше сообщение',
      },
      ids: {
        postVotePrefix: 'post-',
      },
    },
    quoteBubble: {
      bubbleId: 'quote-bubble',
      iconUrl:
        'http://www.iconsearch.ru/uploads/icons/crystalclear/16x16/comment.png',
      postSel: '.post[id]',
      topicId: 'pun-viewtopic',
      offsetX: -2,
      offsetY: -2,
    },
    quotePostLink: {
      selectors: {
        cite: '.quote-box>cite',
        inlineQuote: '#pun-viewtopic .pl-quote > a',
        post: (id) => `.post${id}`,
        postRoot: '.post',
      },
      linkTemplates: {
        sameTopic: (postId) => postId,
        otherTopic: (pid, postId) => `/viewtopic.php?pid=${pid}${postId}`,
      },
    },
    replaceDash: {
      paragraphSelector: '.post-content p',
      dashRegex: /(^|[\s\u00A0])-(?=[\s\u00A0])/g,
    },
    replaceQuotes: {
      selector: '.post-content p',
      regex: /"([^"]*?)"/g,
    },
    replyCharCounter: {
      settingsMenuSection: 'settings',
      toggleInsertAfter: '',
      selectors: {
        textarea: '#main-reply',
        insertAfter: '',
        defaultBefore: '.formsubmit',
      },
      options: {
        stripMaskBBCode: true,
        useGraphemeCounter: true,
        watchProgrammaticChanges: true,
      },
    },
    replyHotkeys: {
      selectors: {
        textarea: '#main-reply',
        insertAfter: '.preview',
        defaultBefore: '.formsubmit',
        submit: '.submit',
      },
      texts: {
        trigger: '?',
        title: 'Горячие клавиши',
        close: 'Esc',
      },
      HOTKEYS: [
        ['Ctrl+KeyB', ['[b]', '[/b]', 'жирный']],
        ['Ctrl+KeyI', ['[i]', '[/i]', 'курсив']],
        ['Ctrl+KeyU', ['[u]', '[/u]', 'подчёркнутый']],
        ['Ctrl+KeyS', ['[s]', '[/s]', 'зачёркнутый']],
        ['Ctrl+KeyL', ['[align=left]', '[/align]', 'выравнивание влево']],
        ['Ctrl+KeyR', ['[align=right]', '[/align]', 'выравнивание вправо']],
        ['Ctrl+KeyE', ['[align=center]', '[/align]', 'выравнивание по центру']],
        ['Ctrl+KeyK', ['[url=https://]', '[/url]', 'ссылка']],
        ['Ctrl+KeyG', ['[spoiler="…"]', '[/spoiler]', 'спойлер']],
        ['Ctrl+KeyH', ['[hide=999999]', '[/hide]', 'скрытый текст']],
        ['Alt+KeyV', ['[video]', '[/video]', 'видео']],
        ['Ctrl+KeyQ', ['[quote]', '[/quote]', 'цитата']],
        ['Ctrl+BracketLeft', ['[code]', '[/' + 'code]', 'код']],
        ['Alt+KeyC', ['[color=maroon]', '[/color]', 'цвет']],
        ['Alt+KeyT', ['[table][tr][td]', '[/td][/tr][/table]', 'таблица']],
        ['Ctrl+Shift+KeyD', ['[add]', '', 'добавлено спустя']],
        ['Ctrl+Shift+KeyA', ['[abbr="…"]', '[/abbr]', 'поясняющий текст']],
        ['Ctrl+Shift+KeyM', ['[mark]', '[/mark]', 'маркированный текст']],
        ['Alt+KeyH', ['[hr]', '', 'горизонтальная линия']],
      ],
    },
    scrollRails: {
      classes: {
        up: '.scroll-rail.rail-up',
        down: '.scroll-rail.rail-down',
      },
      edgeOffset: 80,
    },
    settingsMenu: {
      texts: {
        open: 'Меню',
      },
      sections: {
        themes: {
          title: 'Темы',
          mount: 'themeSwitcher:initSection',
        },
        links: {
          title: 'Полезные ссылки',
          items: [
            {
              text: 'Правила',
              href: 'https://kindredspirits.ru/viewtopic.php?id=32',
              target: '_blank',
              rel: 'noopener noreferrer',
            },
            {
              text: 'F.A.Q.',
              href: 'https://kindredspirits.ru/viewtopic.php?id=33',
              target: '_blank',
              rel: 'noopener noreferrer',
            },
            {
              text: 'Сетка ролей и внешности',
              href: 'https://kindredspirits.ru/pages/characters',
              target: '_blank',
              rel: 'noopener noreferrer',
            },
            {
              text: 'Хронология',
              href: 'https://kindredspirits.ru/pages/chrono',
              target: '_blank',
              rel: 'noopener noreferrer',
            },
            {
              text: 'Банк',
              href: 'https://kindredspirits.ru/pages/bank',
              target: '_blank',
              rel: 'noopener noreferrer',
            },
            {
              text: 'Склад',
              href: 'https://kindredspirits.ru/pages/newbeginning',
              target: '_blank',
              rel: 'noopener noreferrer',
            },
          ],
        },
        games: {
          title: 'Игры',
          items: [
            {
              text: 'Гадание Таро',
              href: 'https://kindredspirits.ru/pages/tarot',
              target: '_blank',
              rel: 'noopener noreferrer',
            },
          ],
        },
        settings: {
          title: 'Настройки',
        },
      },
    },
    stickerPack: {
      dataUrl: 'https://feathertail.ru/images/stickers/stickers.json',
      buttonAfterId: 'button-smile',
      buttonIcon: '/i/blank.gif',
      myTabName: 'Свои',
      storageKey: 'stickerPackUserData',
      hideMyGroupId: 3,
      maxJsonSize: 65000,
      maxUserStickers: 200,
      apiUrl: '/api.php',
      apiSetMethod: 'storage.set',
      apiGetMethod: 'storage.get',
      cacheKey: 'stickerPackForumPacks_v1',
      cacheTtlMs: 1000 * 60 * 60 * 24,
      lastTabKey: 'stickerPackLastTab',
      messages: {
        buttonTitle: 'Стикеры',
        inputPlaceholder: 'URL стикера',
        addButtonLabel: '+',
        removeTitle: 'Удалить',
        toastInvalidUrl: 'Некорректная ссылка на изображение',
        toastTooManyStickers:
          'Слишком много стикеров, последний не был сохранён',
        toastUserLimitReached: 'Слишком много стикеров, достигнут лимит',
        toastUserSaveError: 'Изменения не сохранились, что-то пошло не так',
        toastStorageError: 'Стикеры не сохранились, что-то пошло не так',
        toastStorageCorrupted:
          'Стикеры в хранилище были повреждены, пришлось их сбросить. Резервная копия строки сохранена локально.',
        toastUserLoadWarning:
          'Твои стикеры не прогрузились, придется пользоваться форумными',
        toastForumLoadError:
          'Стикеры не грузятся, что-то пошло не так. Может, поможет перезагрузка страницы?',
      },
    },
    stickyNav: {
      enabled: true,
      targets: [
        {
          selector: '#pun-navlinks',
          scrolledClass: 'nav-scrolled',
          threshold: 0,
        },
        {
          selector: '#pun-ulinks',
          scrolledClass: 'user-scrolled',
          threshold: 345,
        },
      ],
    },
    textReplace: {
      rules: [
        {
          selector: '#navadmin',
          search: 'Администрирование',
          replace: 'АМС',
        },
        {
          selector: 'li.item1 span',
          search: 'Всего тем: ',
          replace: 'Тем: ',
        },
        {
          selector: 'li.item2 span',
          search: 'Всего сообщений: ',
          replace: 'Сообщений: ',
        },
        {
          selector: 'li.item3 span',
          search: 'Зарегистрированных пользователей: ',
          replace: 'Жителей: ',
        },
        {
          selector: 'li.item4 span',
          search: 'Последним зарегистрировался: ',
          replace: 'Приветствуем: ',
        },
      ],
    },
    themeSwitcher: {
      storage: { key: 'mybb.display.v1', instance: 'winter2025' },
      defaults: { style: 'winter', scheme: 'light', view: 'desktop' },
      styles: [
        { id: 'classic', label: 'Classic' },
        { id: 'winter', label: 'Winter' },
      ],
      htmlFrameSelector:
        'iframe.html_frame, .html-post-box iframe.html_frame, .html-content iframe.html_frame',
      iframeCss: [
        'https://forumstatic.ru/styles/001c/8d/fd/style.1766488328.css',
      ],
      selectors: {
        root: 'html',
        targets: {
          style: 'html',
          scheme: 'body',
          view: 'html',
        },
        controls: {
          style: '[data-display-style]',
          scheme: '[data-display-scheme]',
          view: '[data-display-view]',
          forceMobileCheckbox: '#forceMobileToggle',
        },
        ui: {
          schemeMount: '#stylelist',
          styleMount: '[data-style-mount]',
        },
      },
      classes: {
        stylePrefix: '',
        schemeLight: 'light',
        schemeDark: 'dark',
        forceMobile: 'force-mobile',
        activeControl: 'is-active',
      },
    },
    topicAccessGuard: {
      debug: false,
      listReplacementText: 'Доступ запрещён',
      overlay: {
        title: 'Доступ запрещён',
        text: 'У вас нет доступа к этой теме.',
        homeUrl: '/',
        showBackButton: true,
      },
      behavior: {
        hideInLists: true,
        blockView: true,
        disablePosting: true,
        useObserver: true,
      },
      users: [
        {
          userId: 0,
          login: '',
          block: {
            topicIds: [],
            subjectIncludes: [''],
          },
        },
      ],
    },
    userActivityIndicator: {
      selectors: {
        post: '.post',
        authorBlock: '.post-author',
        authorLink: '.pa-author > a',
        lastVisit: '.pa-last-visit',
        activeTime: '.pa-online',
      },
      classes: {
        authorOnlineRoot: 'online',
        linkOnline: 'online',
        linkOffline: 'offline',
        indicatorOnline: 'indOnline',
        indicatorOffline: 'indOffline',
      },
      texts: {
        lastVisitPrefix: 'Последний визит:',
        activePrefix: 'Активен',
        titleOnline: 'Онлайн {{time}}',
        titleOffline: 'Был(а) онлайн {{time}}',
      },
    },
    usershow: {
     rootSelector: '#pun-main',
     messageSelectors: ['.post-content', '.postmsg'],
     alwaysUsers: ['Kayden Moore'],
     alwaysGroups: [1],
     showAllowedListInStub: true,
     citeText: 'Скрытый текст:',
     stubText: 'Скрытый текст доступен только определённым пользователям.',
     prehide: true,
   },
  };
})();










